#define MYI2CCLK LATBbits.LATB6
#define MYI2CCLKT TRISBbits.TRISB6
#define MYI2CDATA LATBbits.LATB7
#define MYI2CDATAT TRISBbits.TRISB7
#define MYI2CDATAIN PORTBbits.RB7
#define MYI2CDELAY __asm nop __endasm
#define SETI2CDATAT(x) (MYI2CDATAT=(x)?1:0)


